visimp/visimp

_site/README/index.html, lua/visimp/impatient.lua, lua/visimp/impatient/cachepack.lua, lua/visimp/languages/css.lua, lua/visimp/languages/go.lua, lua/visimp/languages/html.lua, lua/visimp/languages/javascript.lua, lua/visimp/languages/json.lua, lua/visimp/languages/lua.lua, lua/visimp/languages/php.lua, lua/visimp/layers/statusline.lua, lua/visimp/layers/statusline/mode.lua, lua/visimp/layers/telescope.lua, lua/visimp/pak/count.lua, lua/visimp/pak/logic.lua, lua/visimp/pak/window.lua
I want to give a unique feel to `visimp`. `lualine` custom components will be used to be light on resources and minimal in space taken upon the screen, while still providing complete information and a clear view of the editing status.
=> In-house statusline components

lua/visimp/layers/cmp.lua
Closes #43.
References:
- https://github.com/hrsh7th/cmp-nvim-lsp/issues/38#issuecomment-1279744539
=> cmp.update_capabilities -> cmp.default_capabilities

lua/visimp/languages/ocaml.lua
=> fix: ocaml lsp

lua/visimp/languages/lua.lua
=> sumneko_lua -> lua_ls

lua/visimp/languages/lua.lua, lua/visimp/languages/swift.lua, lua/visimp/layers/autopairs.lua, lua/visimp/layers/cmp.lua, lua/visimp/layers/grammarly.lua, lua/visimp/layers/icons.lua, lua/visimp/layers/lsp.lua, lua/visimp/layers/lspformat.lua, lua/visimp/layers/lspsignature.lua, lua/visimp/layers/nvimtree.lua, lua/visimp/loader.lua, lua/visimp/pak/init.lua, lua/visimp/setup.lua
Added layers for ```nvim-tree/nvim-tree.lua``` and ```nvim-tree/nvim-web-devicons```
=> feat: nvim tree and dev icons layers

docs/CONFIG.md, docs/layers/SNIPPET.md, lua/visimp/languages/agda.lua, lua/visimp/languages/lua.lua, lua/visimp/layers/snippet.lua
Closes #18. Waiting for
to be closed first.
=> Agda language layer

.stylua.toml, stylua.toml
=> fix: remove duplicate (.)stylua

lua/visimp/languages/typst.lua
Follow up to: https://github.com/uben0/tree-sitter-typst/issues/7
https://github.com/nvim-treesitter/nvim-treesitter/pull/6110
=> feat: Typst (treesitter) grammar

docs/layers/LANGUAGES.md, lua/visimp/language.lua, lua/visimp/languages/agda.lua, lua/visimp/languages/ampl.lua, lua/visimp/languages/bash.lua, lua/visimp/languages/c.lua, lua/visimp/languages/coq.lua, lua/visimp/languages/csharp.lua, lua/visimp/languages/css.lua, lua/visimp/languages/go.lua, lua/visimp/languages/haskell.lua, lua/visimp/languages/hcl.lua, lua/visimp/languages/html.lua, lua/visimp/languages/java.lua, lua/visimp/languages/javascript.lua, lua/visimp/languages/json.lua, lua/visimp/languages/latex.lua, lua/visimp/languages/lean.lua, lua/visimp/languages/lua.lua, lua/visimp/languages/ocaml.lua, lua/visimp/languages/php.lua, lua/visimp/languages/python.lua, lua/visimp/languages/rust.lua, lua/visimp/languages/svelte.lua, lua/visimp/languages/swift.lua, lua/visimp/languages/toml.lua, lua/visimp/languages/typst.lua, lua/visimp/languages/vue.lua
=> New language layer API

_init.lua, docs/CONFIG.md, docs/languages/IDRIS.md, docs/layers/LANGUAGES.md, lua/visimp/languages/idris.lua, lua/visimp/languages/prolog.lua
Using vimscript plugin with `ftdetect`, `ftplugin`, `indent`, `snippets` until Treesitter parser/LSP become available on Neovim.
Closes #56.
=> Prolog language layer

lua/visimp/languages/c.lua
Fixes bug reported by @specialfish9.
=> fix: c layer

lua/visimp/layers/lsp.lua, lua/visimp/layers/snippet.lua, lua/visimp/loader.lua, lua/visimp/setup.lua
Closes #90.
Also fixes a bug I encountered while debugging (setting a default layer to `false` would not actually disable it). Also fixes some typos in comments.
=> Fix: <Tab> not working + default layers disabling

docs/CONFIG.md, docs/LAYER.md, docs/layers/COMMENT.md, lua/visimp/layer.lua, lua/visimp/layers/comment.lua, lua/visimp/layers/grammarly.lua, lua/visimp/loader.lua, lua/visimp/setup.lua
=> chore: deprecate 'comment' layer

docs/layers/BLANKLINE.md, docs/layers/RAINBOW.md, lua/visimp/layer.lua, lua/visimp/layers/blankline.lua
Closes #93. Will be a draft until I figure how to actually make it work on the `blankline` side, too.
=> Feat: `rainbow` + `blankline` layers integration

.github/workflows/main.yml, docs/CONTRIBUTING.md, docs/languages/LEAN.md, lua/visimp/bind.lua, lua/visimp/bridge.lua, lua/visimp/language.lua, lua/visimp/layer.lua, lua/visimp/layers/cmp.lua, lua/visimp/layers/statusline/mode.lua, lua/visimp/loader.lua, lua/visimp/pak.lua, lua/visimp/pak/count.lua, lua/visimp/pak/init.lua, lua/visimp/pak/window.lua, lua/visimp/setup.lua
The Lua Language Server provides additional linting over luacheck. It is also the LSP chosen by visimp, and the project already features a .luarc.json.
=> ci: Lua Language Server lint

README.md, lua/visimp/setup.lua
I didn't find any other occurrences of `lucat1/visimp`, but I've searched only through GitHub's explore code. I think a double check won't hurt.
=> Update repository location

README.md
How does hugo render this though? @foxyseta
=> Highlight the warning in the readme

_init.lua, docs/CONFIG.md, lua/visimp/languages/nix.lua
=> feat: nix (closes #123)

lua/visimp/layers/ltex.lua
=> feat: ltex_plus LS

_init.lua, lua/visimp/languages/scheme.lua
=> feat: "scheme" language layer

lua/visimp/layers/typos.lua
=> feat: typos layer

.github/workflows/main.yml, .typos.toml, lua/visimp/bind.lua, lua/visimp/layers/defaults.lua, lua/visimp/pak/git.lua
It is a step under the "lint" job.
=> ci: source code spellchecker

lua/visimp/layers/fugitive.lua, lua/visimp/layers/neogit.lua
This commit description was typed using neogit.
---
Closes #131.
Lean LS seems not to like this. The following error is printed twice:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/uri.lua:82: Invalid buffer id: 19
stack traceback:
[C]: in function 'nvim_buf_get_name'
/usr/share/nvim/runtime/lua/vim/uri.lua:82: in function 'uri_from_bufnr'
...are/nvim/site/pack/paks/start/lean.nvim/lua/lean/lsp.lua:114: in function <...are/nvim/site/pack/paks/start/lean.nvim/lua/lean/lsp.lua:113>
```
I opened https://github.com/Julian/lean.nvim/issues/378 upstream.
=> feat: neogit layer
